version: "3.7"
services:
  ksdp-middleware:
    image: yijun9124/ksdp-service-middleware
    depends_on:
      - ksdp-db
      - mqtt-broker
    ports:
      - "7667:7667"
    environment:
      - LOCALHOST
      - DB_HOST
      - DB_PORT
      - MQTT_HOST
      - CONTROLLER_URL
      - MIDDLEWARE_URL
      - CRANE_ID_MATERIAL_INPUTS
      - CRANE_MATERIAL_INPUTS_PRIORITY
      - CRANE_MATERIAL_INPUTS_RESET_POSITION
      - CRANE_ID_MATERIAL_UPLOAD
      - CRANE_MATERIAL_UPLOAD_PRIORITY
      - CRANE_MATERIAL_UPLOAD_RESET_POSITION
    restart: always
  cranemagic-web:
    image: yijun9124/cranemagic-service-webapi
    depends_on:
      - ksdp-db
      - mqtt-broker
    ports:
      - "6776:6776"
    environment:
      - LOCALHOST
      - DB_HOST
      - DB_PORT
      - MQTT_HOST
      - CONTROLLER_URL
      - MIDDLEWARE_URL
      - CRANE_ID_MATERIAL_INPUTS
      - CRANE_MATERIAL_INPUTS_PRIORITY
      - CRANE_MATERIAL_INPUTS_RESET_POSITION
      - CRANE_ID_MATERIAL_UPLOAD
      - CRANE_MATERIAL_UPLOAD_PRIORITY
      - CRANE_MATERIAL_UPLOAD_RESET_POSITION
    restart: always
  cranemagic-controller-mock:
    image: yijun9124/cranemagic-controller-mock
    ports:
      - "9090:8888"
    environment:
      - LOCALHOST
      - DB_HOST
      - DB_PORT
      - MQTT_HOST
      - CONTROLLER_URL
      - MIDDLEWARE_URL
    restart: always
  cranemagic-mqtt-cms:
    image: yijun9124/cranemagic-service-mqtt-cms
    depends_on:
      - ksdp-db
      - mqtt-broker
    environment:
      - LOCALHOST
      - DB_HOST
      - DB_PORT
      - MQTT_HOST
      - CONTROLLER_URL
      - MIDDLEWARE_URL
      - CRANE_ID_MATERIAL_INPUTS
      - CRANE_MATERIAL_INPUTS_PRIORITY
      - CRANE_MATERIAL_INPUTS_RESET_POSITION
      - CRANE_ID_MATERIAL_UPLOAD
      - CRANE_MATERIAL_UPLOAD_PRIORITY
      - CRANE_MATERIAL_UPLOAD_RESET_POSITION
    restart: always
  cranemagic-frontend-nginx:
    image: yijun9124/cranemagic-frontend-wms-nginx
    depends_on:
      - ksdp-db
      - mqtt-broker
    ports:
      - "80:80"
    restart: always
  mqtt-broker:
    image: yijun9124/cranemagic-mosquitto
    ports:
      - "1883:1883"
      - "1884:1884"
      - "8083:8083"
      - "8084:8084"
    restart: always
  ksdp-db:
    image: yijun9124/ksdp-database
    ports:
      - "6612:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
    restart: always
    volumes:
      - ./data:/var/lib/mysql
